### ISSUE TITLE
Toast - No component factory found for n Error in production (--prod)

### ISSUE THREAD

**Issue by naveedahmed1** [driftyco/ionic#11485]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When running app in production mode, it throws error:

```
main.js:1 ERROR Error: Uncaught (in promise): Error: No component factory found for n. Did you add it to @NgModule.entryComponents?
Error: No component factory found for n. Did you add it to @NgModule.entryComponents?
```

Below is how I am creating it:

```
let toast = this.toastCtrl.create({
      message: 'User was added successfully',
      duration: 3000
    });
    toast.present();
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Unfortunately, i cannot reproduce this issue, would you mind posting a minimal repo we could use to reproduce this issue?

**Comment by naveedahmed1** [comment]
Let me share, when I use it directly in component like below code it works:

```
constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen, private toastCtrl: ToastController) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();
    });

    let toast = this.toastCtrl.create({
        message: 'This is a test alert!',
        duration: 3000
    });
    toast.present();
  }
```

But if I create a service and use it to show toast, it throws error.

To reproduce error, create a new ionic project 

Add a service:
```

import { Injectable } from '@angular/core';
import { ToastController } from 'ionic-angular';

@Injectable()
export class GlobalService {

    constructor(public toastCtrl: ToastController) {}

    showAlert() {
        let toast = this.toastCtrl.create({
            message: 'This is a test alert',
            duration: 3000
        });
        toast.present();
    }
}
```

Update App component with below code:

```

import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { HomePage } from '../pages/home/home';
import { GlobalService } from './global.service';
@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = HomePage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen, private globalService: GlobalService) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();
    });

    globalService.showAlert();
  }
} 

```

Add android platform, and run below command:

`ionic run android --prod`

It wont show any toast. While the device is connected to your computer, open Remote Devices from Chrome Developer Tools, and check the console. It would show the error.


```
main.js:1 ERROR Error: Uncaught (in promise): Error: No component factory found for t. Did you add it to @NgModule.entryComponents?
Error: No component factory found for t. Did you add it to @NgModule.entryComponents?
```

**Comment by badpenguin** [comment]
I've just got the same error with AlertController. Will try to rollback from ionic-app-script 1.3.6 to lower version.

**Comment by naveedahmed1** [comment]
Same issue with LoadingController.

**Comment by phutsa** [comment]
Yes, I have this problem toast and loading is not show and error like above when I run with --prod but without it working fine. waiting to solve soon.

**Comment by naveedahmed1** [comment]
Seems its fixed in https://github.com/driftyco/ionic-app-scripts/blob/master/CHANGELOG.md#137-2017-05-04

**Comment by dalibor983** [comment]
Yes, this is working in 1.3.7 version.
