### ISSUE TITLE
ionic 3 error virtual scroll

### ISSUE THREAD

**Issue by gbelmm** [driftyco/ionic#11093]
![captura de pantalla 2017-04-06 a las 12 04 07](https://cloud.githubusercontent.com/assets/731936/24761314/6037152a-1ac1-11e7-89fc-34d85a685e31.png)

![captura de pantalla 2017-04-06 a las 12 06 47](https://cloud.githubusercontent.com/assets/731936/24761435/b49d81da-1ac1-11e7-8370-c71e9813ffa2.png)

simple code

![captura de pantalla 2017-04-06 a las 12 04 51](https://cloud.githubusercontent.com/assets/731936/24761337/70683ad2-1ac1-11e7-95f4-7716558a1b2c.png)

**Comment by manucorporat** [comment]
Looks like there is an issue when the number of items is == 0.

Fixed and added new tests: https://github.com/driftyco/ionic/commit/5e142a06cc2af2aa95b0446e379bcbeb80f35dad

**Comment by szerner** [comment]
@manucorporat : yes, I have these crashes too when the lists gets empty through filter operations.

**Comment by manucorporat** [comment]
@szerner @gbelmm could you guys try this new nightly release?
 ionic-angular@3.0.0-201704061529

**Comment by gbelmm** [comment]
it works

**Comment by szerner** [comment]
Hm, now I get a bunch of Typescript Errors when I try to "ionic serve":

```
[17:33:59]  ionic-app-scripts 1.3.0
[17:33:59]  watch started ...
[17:33:59]  build dev started ...
[17:33:59]  clean started ...
[17:33:59]  clean finished in 4 ms
[17:33:59]  copy started ...
[17:33:59]  transpile started ...
[17:34:04]  typescript: ...te/proj/node_modules/ionic-angular/components/slides/slides.d.ts, line: 568
            Cannot find name 'SlideElement'.

     L567:  /** @hidden */
     L568:  clickedSlide: SlideElement;
[17:34:04]  typescript: ...te/proj/node_modules/ionic-angular/components/slides/slides.d.ts, line: 570
     L569:  /** @hidden */

            Cannot find name 'SlideContainer'.

```

and some more.

**Comment by szerner** [comment]
I reverted back to `ionic-angular@3.0.0` for now and my app builds again.

**Comment by m00g33k** [comment]
Still having issues on this. 
Also having this warning message:

Virtual Scroll: Please provide an "approxItemHeight" input to ensure proper virtual scroll rendering
virtual-util.js:24 Uncaught TypeError: Cannot read property 'length' of undefined


![screenshot from 2017-04-10 11-58-23](https://cloud.githubusercontent.com/assets/1843525/24845503/2871dc70-1de5-11e7-9ffd-19505fac9c76.png)

**Comment by m00g33k** [comment]
I had it surrounded with an *ngIf so that it would only show if there's an item in the array but it doesn't show. It says: Virtual Scroll: Please provide an "approxItemHeight" input to ensure proper virtual scroll rendering

**Comment by Rockforced** [comment]
@m00g33k having the same issue with the undefined records

**Comment by amrsh** [comment]
After I updated to 3.0.1 I still got property 'top' error, but found that this was due to my list being undefined, not empty (which it was upon load even though initialized to an empty array in a separate service). In case helpful to others, this worked for me:

```javascript
<ion-list [virtualScroll]="list.length ? list : []">
```

**Comment by HashmatWaziri** [comment]
@amrsh , you are right the list needs to be defined for example : 
 
**# IONIC 3**
**home.html**
       
`<ion-list [virtualScroll]="results" [approxItemHeight]="'132px'">`
      `<ion-item *virtualItem="let result;let i=index" >`
      `<h2 ion-text left> {{ i+1}} &nbsp; {{ result.title}}</h2>`
      `<p>{{result.ReleaseDate}} </p>`
      `<ion-icon item-right></ion-icon>`
      `<ion-icon (click)="download(result.audio, result.file_name)" item-right name="download"
              >`
      `</ion-icon>`
     `<ion-icon item-right (click)="open(result.file_name)" name="play"></ion-icon>`
     ` </ion-item>`
      `</ion-list>`

**home.ts**

`export class HomePage {`
`constructor(public navCtrl: NavController) {`
  `  this.results = [];`
  ` this._unfilteredResults = [];`
  ` this._usesFilter = false;`
`}`
`......`
'}'

**Comment by Douglasfeuser** [comment]
still getting this error, is there any fix or workaround for this? i'm using version 3.1.2.

**Comment by beckah** [comment]
Seconding what @Douglasfeuser said
