### ISSUE TITLE
bug: Cannot use 'ionic build ios' after cordova update

### ISSUE THREAD

**Issue by bandojulio** [driftyco/ionic#5252]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>After I updated cordova from 5.4.0 to 6.0.0, I am unable to run the command "ionic build ios". It shows the error:

module.js:339
    throw err;
    ^

Error: Cannot find module 'sax'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/elementtree/lib/parsers/sax.js:3:11)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

Before this it was working fine.</span>

<span is-issue-template></span>

**Comment by bandojulio** [comment]
I found the solution, I reinstalled cordova using "sudo". Now it works.
