### ISSUE TITLE
bug: 8.7.1 breaks reordering, works on 8.7.0

### ISSUE THREAD

**Issue by vesper8** [driftyco/ionic#30600]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [x] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [x] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

I'm using @ionic/core and @ionic/vue

On 8.7.0 all the examples from https://ionicframework.com/docs/api/reorder work perfectly.

On 8.7.1 none of them work.

### Expected Behavior

 Should work

### Steps to Reproduce

install ionic/cli and make a brand new app with vue

copy one of the examples from https://ionicframework.com/docs/api/reorder

reordering is broken

change package.json to fixed version 8.7.0

npm or yarn

everything works

### Code Reproduction URL

https://github.com

### Ionic Info

[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - /opt/homebrew/lib/node_modules/@ionic/cli/lib/project/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/lib/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/bin/ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'

       Require stack:
       - /opt/homebrew/lib/node_modules/@ionic/cli/lib/project/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/lib/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/index.js
       - /opt/homebrew/lib/node_modules/@ionic/cli/bin/ionic

Ionic:

   Ionic CLI       : 7.2.1 (/opt/homebrew/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 8.7.0

Capacitor:

   Capacitor CLI      : 7.4.2
   @capacitor/android : not installed
   @capacitor/core    : 7.4.2
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v24.3.0 (/opt/homebrew/Cellar/node/24.3.0/bin/node)
   npm    : 11.4.2
   OS     : macOS Unknown

(base)

**Comment by jakubforman** [comment]
Since version 8.7.0 (also in version 8.7.1) there is a complete non-functionality of `ion-reorder`.

Reproduction: https://github.com/jakubforman/ion-reorder-bug

It seems to work, but the moment you drag the element, it disappears. In addition, when the drag and drop is finished, the problem occurs that no information is available.

```html
<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-title>
      Tab 1
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">Tab 1</ion-title>
    </ion-toolbar>
  </ion-header>

<ion-list>
  <!-- The reorder gesture is disabled by default, enable it to drag and drop items -->
  <!-- Casting $event to $any is a temporary fix for this bug https://github.com/ionic-team/ionic-framework/issues/24245 -->
  <ion-reorder-group [disabled]="false" (ionReorderEnd)="handleReorderEnd($any($event))">
    <ion-item>
      <ion-label> Item 1 </ion-label>
      <ion-reorder slot="end"></ion-reorder>
    </ion-item>

    <ion-item>
      <ion-label> Item 2 </ion-label>
      <ion-reorder slot="end"></ion-reorder>
    </ion-item>

    <ion-item>
      <ion-label> Item 3 </ion-label>
      <ion-reorder slot="end"></ion-reorder>
    </ion-item>

    <ion-item>
      <ion-label> Item 4 </ion-label>
      <ion-reorder slot="end"></ion-reorder>
    </ion-item>

    <ion-item>
      <ion-label> Item 5 </ion-label>
      <ion-reorder slot="end"></ion-reorder>
    </ion-item>
  </ion-reorder-group>
</ion-list>
</ion-content>

```

```typescript
import {Component} from '@angular/core';
import {
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonItem,
  IonLabel,
  IonReorder,
  IonReorderGroup, IonList
} from '@ionic/angular/standalone';
import {ExploreContainerComponent} from '../explore-container/explore-container.component';
import {ReorderEndCustomEvent} from "@ionic/angular";

@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss'],
  imports: [IonHeader, IonToolbar, IonTitle, IonContent, IonItem, IonLabel, IonReorder, IonReorderGroup, IonList],
})
export class Tab1Page {
  constructor() {
  }

  handleReorderEnd(event: ReorderEndCustomEvent) {
    // The `from` and `to` properties contain the index of the item
    // when the drag started and ended, respectively
    console.log('Dragged from index', event.detail.from, 'to', event.detail.to);

    // Finish the reorder and position the item in the DOM based on
    // where the gesture ended. This method can also be called directly
    // by the reorder group.
    event.detail.complete();
  }
}

```

<img width="1677" height="960" alt="Image" src="https://github.com/user-attachments/assets/2dd0897b-61b0-499c-84eb-cf2570bb2382" />

**Comment by vesper8** [comment]
@jakubforman thank you for confirming the issue. In my case it does work perfectly with 8.7.0 however, it only breaks in 8.7.1. Intriguing that you're having issues with 8.7.0 as well.

**Comment by mikebrucker** [comment]
following.

ran into this today as well updating form 8.6 to 8.7.1. can confirm that downgrading to 8.7.0 for @ionic/react works.

event.detail is `detail: {from: undefined, to: -1, complete: ƒ}` and ion-item disappears upon starting the drag.

**Comment by brandyscarney** [comment]
Thank you for the issue! This has been fixed in [v8.7.2](https://github.com/ionic-team/ionic-framework/releases/tag/v8.7.2). Please open a new issue if you run into anything else. 🙂
